/* Generated by AN DISI Unibo */ 
package it.unibo.sonarwrapper

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024
import java.io.*

class Sonarwrapper ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
				lateinit var p : Process
				lateinit var reader : BufferedReader 
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name: STARTING...")
						
									const val DFREE = System.getenv("DFREE")
									
									// python script given by the client
									try {
										p = Runtime.getRuntime().exec("python sonar.py")
										reader = BufferedReader(InputStreamReader(p.getInputStream()))
									} catch(e : Exception) {
										println("sonardevice sonarStart ERROR: $e")
									}
						CommUtils.outmagenta("$name: initialization complete")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="sendsonardata", cond=doswitch() )
				}	 
				state("sendsonardata") { //this:State
					action { //it:State
						
									try {
										var D = reader.readLine()
										if(D != null) {
											val payload = "distance( ${D} )"
											val distance = MsgUtil.buildDispatch("sonarwrapper", "distance", payload, "alarmwrapper")
											
											forward(distance)
										}
									} catch(e : Exception) {
										println("sonarwrapper sendsonardata ERROR: $e")
									}
						if(  D < DFREE / 2  
						 ){
										val containerWaiting = MsgUtil.buildDispatch("sonarwrapper", "containerWaiting", "1", "cargorobot")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="sendsonardata", cond=doswitch() )
				}	 
			}
		}
} 
