/* Generated by AN DISI Unibo */ 
package it.unibo.cargotest

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargotest ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "start"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		return { //this:ActionBasciFsm
				state("start") { //this:State
					action { //it:State
						CommUtils.outyellow("[cargotest] Inizia")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_start", 
				 	 					  scope, context!!, "local_tout_"+name+"_start", 1000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t01",targetState="richiesta",cond=whenTimeout("local_tout_"+name+"_start"))   
				}	 
				state("richiesta") { //this:State
					action { //it:State
						CommUtils.outyellow("[cargotest] Invia una nuova nuova richiesta")
						request("load_product", "load_product(1)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="loadAccepted",cond=whenReply("load_accepted"))
					transition(edgeName="t03",targetState="loadRefused",cond=whenReply("load_refused"))
				}	 
				state("loadAccepted") { //this:State
					action { //it:State
						CommUtils.outblue("[cargoservice] risposta arrivata")
						
						       val msg=payloadArg(0).toInt()        
						CommUtils.outyellow("[cargotest] $msg ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("loadRefused") { //this:State
					action { //it:State
						
						       val msg=payloadArg(0).toInt()
						CommUtils.outyellow("[cargotest] $msg ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
