/* Generated by AN DISI Unibo */ 
package it.unibo.test

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Test ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "start"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		return { //this:ActionBasciFsm
				state("start") { //this:State
					action { //it:State
						CommUtils.outblue("[test] avviato")
						request("createProduct", "product("{"productId":31,"name":"p31","weight":311}")" ,"ctxcargoservice" )  
						CommUtils.outyellow("[test]  mandata richiesta")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="createdProduct",cond=whenReply("createdProduct"))
				}	 
				state("createdProduct") { //this:State
					action { //it:State
						CommUtils.outyellow("[test] risposta arrivata")
						if( checkMsgContent( Term.createTerm("productid(ID)"), Term.createTerm("createdProduct(ID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								val Msg=payloadArg(0).toInt()         
								CommUtils.outyellow("[cargotest] Richiesta accettata, slot n. $Msg ")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
