/* Generated by AN DISI Unibo */ 
package it.unibo.alarmdevice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Alarmdevice ( name: String, scope: CoroutineScope, isconfined: Boolean=false  ) : ActorBasicFsm( name, scope, confined=isconfined ){

	override fun getInitialState() : String{
		return "init"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		 lateinit var p : Process  
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						CommUtils.outred("$name: STARTING...")
						 p = machineExec("python ledPython25Off.py")  
						
									var timetostop = 0	
									var timetoresume = 0
									var alarm = 0
						CommUtils.outred("$name: initialization complete")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitfordata", cond=doswitch() )
				}	 
				state("waitfordata") { //this:State
					action { //it:State
						CommUtils.outred("$name: waiting for data...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t07",targetState="evaluate",cond=whenDispatch("distance"))
				}	 
				state("evaluate") { //this:State
					action { //it:State
						CommUtils.outred("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val D = payloadArg(0).toInt()  
								if(  alarm == 0  
								 ){if(  D > DFREE  
								 ){if(  timetostop == 0  
								 ){ timetostop = LocalDateTime.now()  
								}
								else
								 {if(  timetostop.plusSeconds(3).isBefore(LocalDateTime.now())  
								  ){ alarm = 1  
								 emit("stop", "stop(1)" ) 
								 CommUtils.outred("$name: STOP")
								 }
								 }
								}
								else
								 { timetostop = 0  
								 }
								}
								else
								 {if(  D <= DFREE  
								  ){if(  timetoresume == 0  
								  ){ timetoresume = LocalDateTime.now()  
								 }
								 else
								  {if(  timetoresume.plusSeconds(3).isBefore(LocalDateTime.now())  
								   ){ alarm = 0  
								  emit("resume", "resume(1)" ) 
								  CommUtils.outred("$name: RESUME")
								  }
								  }
								 }
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitfordata", cond=doswitch() )
				}	 
			}
		}
} 
