/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "start"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		
		       	var Taken_slot=arrayListOf("false","false","false","false","true")
		    	val MAX_LOAD=500
		    	var CURRENT_LOAD=0
		    	var Product_weight = 0
		    	var Reserved_slot = 0
		return { //this:ActionBasciFsm
				state("start") { //this:State
					action { //it:State
						CommUtils.outyellow("[cargoservice] STARTED ")
						delay(5000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting_for_request", cond=doswitch() )
				}	 
				state("waiting_for_request") { //this:State
					action { //it:State
						CommUtils.outyellow("[cargoservice] waiting for request")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t019",targetState="check_product",cond=whenRequest("load_product"))
					interrupthandle(edgeName="t020",targetState="stop",cond=whenEvent("sonar_error"),interruptedStateTransitions)
					transition(edgeName="t021",targetState="check_product",cond=whenEvent("container_trigger"))
				}	 
				state("stop") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sonar_error(CAUSA)"), Term.createTerm("sonar_error(CAUSA)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val M=payloadArg(0) 
								CommUtils.outyellow("[$name] sonar ha emesso un errore causa: $M")
								emit("stop", "stop(si)" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t022",targetState="resume",cond=whenEvent("problem_solved"))
				}	 
				state("resume") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("problem_solved(CAUSA)"), Term.createTerm("problem_solved(CAUSA)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val M=payloadArg(0) 
								CommUtils.outyellow("[$name] sonar ha risolto l'errore causa: $M")
								emit("resume", "resume(ok)" ) 
						}
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting_for_request", cond=doswitch() )
				}	 
				state("check_product") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("container_trigger(X)"), Term.createTerm("container_trigger(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblack("[cargoservice] check del prodotto")
								
												val ID=1
								request("getProduct", "product($ID)" ,"productservice" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t023",targetState="check_load",cond=whenReply("getProductAnswer"))
					interrupthandle(edgeName="t024",targetState="stop",cond=whenEvent("sonar_error"),interruptedStateTransitions)
				}	 
				state("check_load") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("product(JSonString)"), Term.createTerm("product(JsonString)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblack("[cargoservice] arrivato peso")
								
												val Product=payloadArg(0)					
												Product_weight = main.java.Product.getJsonInt(Product, "weight")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="checkSlot", cond=doswitchGuarded({CURRENT_LOAD+ Product_weight <= MAX_LOAD  
					}) )
					transition( edgeName="goto",targetState="too_much_weight", cond=doswitchGuarded({! (CURRENT_LOAD+ Product_weight <= MAX_LOAD  
					) }) )
				}	 
				state("too_much_weight") { //this:State
					action { //it:State
						CommUtils.outyellow("Il carico eccederebbe maxload, non è possibile eseguire la load")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting_for_request", cond=doswitch() )
				}	 
				state("checkSlot") { //this:State
					action { //it:State
						CommUtils.outyellow("[cargoservice] ingresso move product")
						 
									CURRENT_LOAD += Product_weight		      
								    Reserved_slot=0   
								    for(i in 0..4){
									    if (Taken_slot[i]=="false") {
										    Reserved_slot = i+1
										    Taken_slot[i]="true"
										    break;		    	
									    }
								    }
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="moveProduct", cond=doswitchGuarded({Reserved_slot!=0 
					}) )
					transition( edgeName="goto",targetState="slotEsauriti", cond=doswitchGuarded({! (Reserved_slot!=0 
					) }) )
				}	 
				state("slotEsauriti") { //this:State
					action { //it:State
						CommUtils.outyellow("[$name] slot esauriti")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("moveProduct") { //this:State
					action { //it:State
						request("move_product", "product($Reserved_slot)" ,"cargorobot" )  
						CommUtils.outyellow("[cargoservice] richiesta di move al cargo robot mandata")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t025",targetState="load_finished",cond=whenReply("movedProduct"))
					interrupthandle(edgeName="t026",targetState="stop",cond=whenEvent("sonar_error"),interruptedStateTransitions)
				}	 
				state("load_finished") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("result(SLOT)"), Term.createTerm("result(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outblack("Load completata il robot è in home ")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waiting_for_request", cond=doswitch() )
				}	 
			}
		}
} 
