/* Generated by AN DISI Unibo */ 
package it.unibo.hold_observer

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Hold_observer ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "start"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
			
				var Taken_slot=arrayListOf("false","false","false","false","true")
		    	val MAX_LOAD=500
		    	var CURRENT_LOAD=0
		    	var Led = false
		    	var Sonar = false
		return { //this:ActionBasciFsm
				state("start") { //this:State
					action { //it:State
						CommUtils.outblack("$name | start")
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="observe_hold", cond=doswitch() )
				}	 
				state("observe_hold") { //this:State
					action { //it:State
						CommUtils.outblack("$name | Observing hold")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t031",targetState="change_slot_status",cond=whenEvent("slot_changed"))
					transition(edgeName="t032",targetState="change_led_status",cond=whenEvent("led_changed"))
					transition(edgeName="t033",targetState="change_sonar_status",cond=whenEvent("sonar_changed"))
					transition(edgeName="t034",targetState="change_weight",cond=whenEvent("current_weight"))
					transition(edgeName="t035",targetState="updateState",cond=whenRequest("get_hold_state"))
				}	 
				state("change_slot_status") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("slot_changed(ID,status)"), Term.createTerm("slot_changed(ID,status)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
											val Slot = 	payloadArg(0).toInt()
											if (Taken_slot[Slot]=="false") {
												    Taken_slot[Slot]="true"		    	
											    }
											    else{
											    	Taken_slot[Slot]="false"
											    }
								CommUtils.outblack("$name | ho ricevuto un cambio dello slot $Slot che ora vale $Taken_slot[Slot]")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="observe_hold", cond=doswitch() )
				}	 
				state("change_led_status") { //this:State
					action { //it:State
						
										Led = !Led
						CommUtils.outblack("$name | ho ricevuto un cambio dello stato del led che ora vale $Led")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="observe_hold", cond=doswitch() )
				}	 
				state("change_sonar_status") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sonar_changed(status)"), Term.createTerm("sonar_changed(status)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
												Sonar = payloadArg(0)
								CommUtils.outblack("$name | ho ricevuto un cambio dello stato del sonar che ora vale $Sonar")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="observe_hold", cond=doswitch() )
				}	 
				state("change_weight") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("current_weight(weight)"), Term.createTerm("current_weight(weight)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								
											CURRENT_LOAD = 	payloadArg(0).toInt()
								CommUtils.outblack("$name | ho ricevuto un cambio del peso della stiva che ora pesa $CURRENT_LOAD")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="observe_hold", cond=doswitch() )
				}	 
				state("updateState") { //this:State
					action { //it:State
						answer("get_hold_state", "send_hold_state", "hold_state("Taken slot:$Taken_slot; Led:$Led; Sonar:$Sonar; CURRENT_LOAD:$CURRENT_LOAD")"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
