/* Generated by AN DISI Unibo */ 
package it.unibo.sonar_test

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonar_test ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "start"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		 var Counter = 1  
		return { //this:ActionBasciFsm
				state("start") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | started ")
						delay(2000) 
						delay(30000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="simulate_container_arrival", cond=doswitch() )
				}	 
				state("simulate_container_arrival") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | Simulo arrivo container")
						CommUtils.outgray("$name | $Counter | numero dell'iterazione di Sonar Test")
						emit("container_trigger", "container_trigger(1)" ) 
						emit("sonar_changed", "sonar_changed(Container_Individuato)" ) 
						updateResourceRep("slot_changed($Counter,true)" 
						)
						updateResourceRep("sonar_changed(Container_Individuato)" 
						)
						delay(10000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="simulate_container_absence", cond=doswitch() )
				}	 
				state("simulate_container_absence") { //this:State
					action { //it:State
						if(  Counter % 5 == 0  
						 ){CommUtils.outyellow("$name | Simulo sparizione container")
						emit("container_absence", "container_absence(no)" ) 
						emit("sonar_changed", "sonar_changed(Container_Assente)" ) 
						updateResourceRep("slot_changed($Counter,false)" 
						)
						updateResourceRep("sonar_changed(Container_Assente)" 
						)
						delay(10000) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="maybe_fail", cond=doswitch() )
				}	 
				state("maybe_fail") { //this:State
					action { //it:State
						 Counter++  
						if(  Counter % 2 == 0  
						 ){CommUtils.outmagenta("$name | Guasto sonar!")
						emit("sonar_error", "sonar_error(errore)" ) 
						updateResourceRep("led_changed(Acceso)" 
						)
						updateResourceRep("alarm(X)" 
						)
						delay(4000) 
						CommUtils.outmagenta("$name | Sonar ripristinato!")
						emit("problem_solved", "problem_solved(solved)" ) 
						updateResourceRep("led_changed(Spento)" 
						)
						updateResourceRep("problem_solved(solved)" 
						)
						}
						delay(10000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="simulate_container_arrival", cond=doswitch() )
				}	 
			}
		}
} 
