/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "start"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		 
				lateinit var reader : java.io.BufferedReader
			    lateinit var p : Process	
			    var Distance = 0
		return { //this:ActionBasciFsm
				state("start") { //this:State
					action { //it:State
						CommUtils.outblack("$name | start")
						
									p       = Runtime.getRuntime().exec("python sonar.py")
									reader  = java.io.BufferedReader(java.io.InputStreamReader(p.getInputStream()))	
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="measurement", cond=doswitch() )
				}	 
				state("measurement") { //this:State
					action { //it:State
						CommUtils.outblack("nuova misurazione")
						 
									var data = reader.readLine()
									if( data != null ){
										try{ 
											val vd = data.toFloat()
											val v  = vd.toInt()
											
											// filter the data maybe?
											if(v <= 100) 
												Distance = v				
											else 
												Distance = 0
										}catch(e: Exception){
											CommUtils.outred("$name readSonarDataERROR: $e")
										}
									}
									
						CommUtils.outblack("$data")
						if(  Distance > 0  
						 ){CommUtils.outyellow("$name | misurato $Distance cm")
						emit("sonardata", "distanza($Distance)" ) 
						}
						delay(3000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="measurement", cond=doswitch() )
				}	 
			}
		}
} 
