version: '3.8'

services:

  mongodb:
    image: mongo:6.0.4
    container_name: mongodb  
    mem_limit: 512m
    environment:
      - MONGO_INITDB_DATABASE=cargodb
    ports:
      - "27017:27017"
    command: mongod
    networks:
      - iss-network

  cargoserviceqak:
    container_name: cargoserviceqak 
    image: docker.io/natbodocker/cargoserviceqak:1.0
    environment:
      - MONGO_HOST=mongodb
      - SERVICE_IP=localhost
    ports:
      - 8111:8111/tcp
      - 8111:8111/udp
    depends_on:
      - mongodb
    networks:
      - iss-network

networks:
  iss-network:
    external: true

## To use:
## 1. Create network: docker network create iss-network
## 2. Start services: docker-compose -f sprint3-linux.yaml up
## 3. In another terminal: gradle bootRun
